name: Prevent Jupyter Notebook Output

# This section has been updated
# The workflow now runs on a push to any branch EXCEPT the main branch.
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Verify that notebooks are clean
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
          
      - name: Provide rejection message
        if: ${{ failure() }} # This step will only run if the previous step fails
        run: |
          echo "-----------------------------------------------------"
          echo "ERROR: Push rejected."
          echo "Jupyter Notebooks with output cells are not allowed."
          echo "Please clear the output of all notebooks before committing."
          echo "You can clear outputs using the command: 'jupyter nbconvert --clear-output --inplace your_notebook.ipynb'"
          echo "-----------------------------------------------------"
          exit 1
